### ISSUE TITLE
CertConfig is missing `autoRegistration` for issuers

### ISSUE THREAD

**Issue by MartinWeindel** [gardener/gardener-extension-shoot-cert-service#248]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
When creating an issuer with external account binding, the `autoRegistration` field could not be specified.

```yaml
- type: shoot-cert-service
  providerConfig:
    apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
    kind: CertConfig
    shootIssuers:
      enabled: true
    issuers:
      - email: ***********@***.com
        autoRegistration: true
        externalAccountBinding:
          keyID: *********************
          keySecretName: some-credentials
        name: cdf-dev-sap
        server: https://***.com/***/v1/acme/v2/directory
```

**What you expected to happen**:
Should allow to provide `autoRegistration: true`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
