### ISSUE TITLE
If an issuer is defined with wrong server endpoint, the error message should be more helpful

### ISSUE THREAD

**Issue by MartinWeindel** [gardener/gardener-extension-shoot-cert-service#316]
**How to categorize this issue?**

/area control-plane
/kind enhancement

**What would you like to be added**:
If the `server` endpoint is wrongly defined:
e.g. 
```
    - type: shoot-cert-service
      providerConfig:
        apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
        issuers:
          - name: letsencrypt
            email: ...
            server: https://acme-v02.api.letsencrypt.org/.   #wrong, must be: https://acme-v02.api.letsencrypt.org/directory
```

The shoot status only reports some generic error message without details.
```
Issuer "shoot--foo--bar/letsencrypt" is unhealthy: issuer state is "Error" ("Ready" expected)
```
The error message should have be more helpful.
